title: Lukas Racko Blog
email: rackolukas14@gmail.com
baseurl: "" 
url: "http://xrackol.github.io"
twitter_username: jekyllrb
github_username:  xrackol

# Build settings
markdown: kramdown
encoding: utf-8
permalink: /news/:year/:month/:day/:title
